services:
  - type: worker
    name: unified-asset-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python unified_asset_bot.py
    envVars:
      - key: 8646533018:AAFvrtNrWRH9G5QZ92jJm54BZx0OOqXuuOA
        sync: false
